// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post_tags.sql

package database

import (
	"context"
)

const addTagToPost = `-- name: AddTagToPost :exec
INSERT INTO post_tags (post_id, tag_id)
VALUES ($1, $2)
`

type AddTagToPostParams struct {
	PostID int64 `json:"post_id"`
	TagID  int32 `json:"tag_id"`
}

func (q *Queries) AddTagToPost(ctx context.Context, arg AddTagToPostParams) error {
	_, err := q.db.Exec(ctx, addTagToPost, arg.PostID, arg.TagID)
	return err
}

const getPostTags = `-- name: GetPostTags :many
SELECT t.id, t.name FROM tags t
JOIN post_tags pt ON t.id = pt.tag_id
WHERE pt.post_id = $1
`

func (q *Queries) GetPostTags(ctx context.Context, postID int64) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getPostTags, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsByTag = `-- name: GetPostsByTag :many
SELECT p.id, p.user_id, p.comment, p.media_hash, p.media_type, p.media_url, p.thumb_url, p.status, p.created_at, p.updated_at FROM posts p
JOIN post_tags pt ON p.id = pt.post_id
WHERE pt.tag_id = $1 AND p.status = 'completed'
ORDER BY p.created_at DESC
`

func (q *Queries) GetPostsByTag(ctx context.Context, tagID int32) ([]Post, error) {
	rows, err := q.db.Query(ctx, getPostsByTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Comment,
			&i.MediaHash,
			&i.MediaType,
			&i.MediaUrl,
			&i.ThumbUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromPost = `-- name: RemoveTagFromPost :exec
DELETE FROM post_tags 
WHERE post_id = $1 AND tag_id = $2
`

type RemoveTagFromPostParams struct {
	PostID int64 `json:"post_id"`
	TagID  int32 `json:"tag_id"`
}

func (q *Queries) RemoveTagFromPost(ctx context.Context, arg RemoveTagFromPostParams) error {
	_, err := q.db.Exec(ctx, removeTagFromPost, arg.PostID, arg.TagID)
	return err
}

const setPostTags = `-- name: SetPostTags :exec
DELETE FROM post_tags WHERE post_id = $1
`

func (q *Queries) SetPostTags(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, setPostTags, postID)
	return err
}
